version: '3.7'

services:

  backend:
    image: tiagostutz/chimpassist-server:0.1.5-alpine
    ports:
      - 3134:3134
    environment:
      - MONGO_CONNECTION_URL=mongodb://root:root@mongo:27017/?authMechanism=SCRAM-SHA-1
      - MQTT_BROKER_HOST=mqtt://mqtt:1883
    networks:
      - chimpassist-demo        

  back-office:
    image: tiagostutz/chimpassist-back-office-ui:0.2.0-alpine
    ports:
      - 3210:80
    environment:  
      - LOGO_SMALL_URL=https://ik.imagekit.io/stutzsolucoes/small_logo_SJ0kUUTmV.png
      - DEFAULT_ATTENDANT_AVATAR_URL=https://ik.imagekit.io/stutzsolucoes/jorge_BkNNIIpQE.png
      - FAV_ICON_URL=https://ik.imagekit.io/stutzsolucoes/small_logo_SJ0kUUTmV.png
      - MAIN_PAGE_TITLE=E-didático atendimento aos estudantes
      - LOGIN_PAGE_TITLE=E-didático - Entre com seu e-mail e senha
      - BACKEND_ENDPOINT=http://localhost:3134
      - FORCE_i18n_LANGUAGE=ptBR
      - AUTHENTICATION_ENDPOINT=http://localhost:3333
      - STATISTICS_ENDPOINT=http://localhost:8000
      - MQTT_BROKER_HOST=http://localhost:8080/mqtt
      - ONLINE_CUSTOMERS_LABEL=Online students
      - OFFLINE_CUSTOMERS_LABEL=Offline students
    networks:
      - chimpassist-demo

  mqtt:
    image: erlio/docker-vernemq
    restart: always
    ports:
      - 1883:1883
      - 8080:8080
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=info
    networks:
      - chimpassist-demo        

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - chimpassist-demo        

networks:
  chimpassist-demo:
    name: chimpassist-demo      