version: '3.5'

services:

  mqtt:
    image: erlio/docker-vernemq
    restart: always
    ports:
      - 1884:1883
      - 8081:8080
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=info

  mongo:
    image: mongo
    ports:
      - 27027:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=n4oehf4c1l!