version: '3.5'

services:

  mqtt:
    image: erlio/docker-vernemq
    restart: always
    ports:
      - 1884:1883
      - 8081:8080
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL=info
